typography_spectrum: 0.0923586068674922
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.021323202876374125
  lightness: 0.3624202876817435
  saturation: 0.28519304608926177
  rhythmicContrast: 0.017134156776592135
opengraph:
  image: null
  type: null
  appId: '307339332686535'
layout_spectrum: 0.07083814684301615
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Ricardo
  email: ricardo.posadas@proscitec.onmicrosoft.com
name: Max Performance Coaching
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
